name: CI
on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: install dependency
      run: |
        chmod +x start.sh
        bash start.sh

    - name: running redroid
      run: |
        docker run -itd --rm --privileged \
            --pull always \
            -v ~/data:/data \
            -p 5555:5555 \
            redroid/redroid:12.0.0_64only-latest

    - name: connect to adb and scrcpy
      env:
        CLOUDFLARED_AUTH_TOKEN : ${{ secrets.CLOUDFLARED_AUTH_TOKEN }}
      run: 'cloudflared tunnel run --token $CLOUDFLARED_AUTH_TOKEN'



